const { Animal } = require('../../db');

module.exports = async () => {
    await Animal.truncate();
    await Animal.bulkCreate([
        {
            name: 'lokito',
            gender: 'male',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2011,
        },
        {
            name: 'lokita',
            gender: 'female',
            species: 'cat',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2005,
        },
        {
            name: 'messi',
            gender: 'male',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2022,
        },
        {
            name: 'jack',
            gender: 'male',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2010,
        },
        {
            name: 'victor',
            gender: 'male',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2020,
        },
        {
            name: 'emily',
            gender: 'female',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2022,
        },
        {
            name: 'victoria',
            gender: 'female',
            species: 'dog',
            status: 'adopted',
            size: 'medium',
            weight: 20,
            vaccines: true,
            // color: colorList[0],
            disability_illness: true,
            castrated: false,
            estimatedBirthYear: 2011,
        },
    ]);
};
